# Generated by Django 5.2.10 on 2026-01-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_delete_pago'),
        ('pagos', '0002_pago_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cashsession'),
        ),
    ]
