# Generated by Django 5.2.10 on 2026-04-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_alter_pago_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
