# Generated by Django 5.2.8 on 2026-05-05 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_cashsession_efectivo_cashsession_tarjeta_and_more'),
        ('pagos', '0005_pago_appointment_id_pago_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('categoria', models.CharField(choices=[('insumos', 'Insumos'), ('laboratorio', 'Laboratorio'), ('alquiler', 'Alquiler'), ('servicios', 'Servicios'), ('sueldos', 'Sueldos'), ('mantenimiento', 'Mantenimiento'), ('otros', 'Otros')], max_length=50)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cashsession')),
            ],
        ),
    ]
