# Generated by Django 5.2.8 on 2026-05-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='afecta_caja',
            field=models.BooleanField(default=True, verbose_name='Afecta caja del día'),
        ),
    ]
