# Generated by Django 5.2.8 on 2026-06-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_compraproveedor_pagocompraproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproveedor',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
