# Generated by Django 5.2.8 on 2026-06-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_compraproveedor_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='protesis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
