# Generated by Django 5.2.8 on 2026-08-18 03:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_pago_protesis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cfe_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='cfe_estado',
            field=models.CharField(choices=[('no_solicitado', 'Sin CFE'), ('pendiente', 'Pendiente CFE'), ('emitido', 'CFE emitido'), ('rechazado', 'CFE rechazado'), ('anulado', 'CFE anulado')], default='no_solicitado', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='cfe_numero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='cfe_pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pago',
            name='cfe_serie',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='cfe_solicitado',
            field=models.BooleanField(default=False, verbose_name='Preparar comprobante electrónico'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cfe_tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='cfe_xml_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pago',
            name='facture_cfe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='tasa_iva_cfe',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
    ]
