# Generated by Django 5.2.8 on 2026-08-19 01:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_pago_protesis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('insumos', 'Insumos'), ('laboratorio', 'Laboratorio'), ('alquiler', 'Alquiler'), ('servicios', 'Servicios'), ('sueldos', 'Sueldos'), ('mantenimiento', 'Mantenimiento'), ('devolucion_paciente', 'Devolución a paciente'), ('otros', 'Otros')], max_length=50),
        ),
        migrations.CreateModel(
            name='DevolucionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('patient_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('appointment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('protesis_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('concepto', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('gasto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucion_paciente', to='pagos.gasto')),
                ('pago_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='pagos.pago')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
