# Generated by Django 5.2.8 on 2026-08-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_pago_cfe_error_pago_cfe_estado_pago_cfe_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, choices=[('debito', 'Débito'), ('credito', 'Crédito')], default='', help_text='Detalle del pago con tarjeta: débito o crédito.', max_length=10),
        ),
    ]
