# Generated by Django 5.2.8 on 2026-08-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_pago_tipo_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cfe_xml_firmado',
            field=models.TextField(blank=True),
        ),
    ]
