# Generated by Django 5.2.8 on 2026-08-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_pago_cfe_xml_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='nc_cfe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='nc_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='nc_numero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='nc_serie',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='nc_xml_firmado',
            field=models.TextField(blank=True),
        ),
    ]
