# Generated by Django 5.2.8 on 2026-08-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_alter_gasto_categoria_devolucionpaciente'),
        ('pagos', '0014_pago_nc_cfe_id_pago_nc_error_pago_nc_numero_and_more'),
    ]

    operations = [
    ]
