# Generated by Django 5.2.8 on 2026-08-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_merge_20260820_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cfe_fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
