# Generated by Django 5.2.8 on 2026-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0016_pago_cfe_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionpaciente',
            name='nc_cfe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devolucionpaciente',
            name='nc_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devolucionpaciente',
            name='nc_fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucionpaciente',
            name='nc_numero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='devolucionpaciente',
            name='nc_serie',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='devolucionpaciente',
            name='nc_solicitada',
            field=models.BooleanField(default=False, verbose_name='Emitir Nota de Crédito'),
        ),
        migrations.AddField(
            model_name='devolucionpaciente',
            name='nc_xml_firmado',
            field=models.TextField(blank=True),
        ),
    ]
