# Generated by Django 5.2.10 on 2026-01-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
