# Generated by Django 5.2.10 on 2026-02-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_delete_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='total_pagos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
