# Generated by Django 5.2.8 on 2026-05-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_cashsession_efectivo_cashsession_tarjeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
