# Generated by Django 5.2.8 on 2026-05-10 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_movimientocaja_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashsession',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, unique=True),
        ),
    ]
