# Generated by Django 5.2.8 on 2026-05-10 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_alter_cashsession_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashsession',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, unique=True),
        ),
    ]
