# Generated by Django 5.2.8 on 2026-05-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_alter_cashsession_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashsession',
            options={},
        ),
    ]
