# Generated by Django 5.2.8 on 2026-07-29 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0010_alter_cashsession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashsession',
            options={'ordering': ['-fecha']},
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio_turno', 'Cambio de turno'), ('control', 'Control'), ('pre_cierre', 'Previo al cierre')], default='cambio_turno', max_length=20)),
                ('responsable', models.CharField(max_length=120)),
                ('saldo_esperado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_contado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('observacion', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos', to='caja.cashsession')),
            ],
            options={
                'verbose_name': 'Arqueo de caja',
                'verbose_name_plural': 'Arqueos de caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
