# Generated by Django 5.2.8 on 2026-09-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_alter_cashsession_options_arqueocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='afecta_resultado',
            field=models.BooleanField(default=True, help_text='Indica si el movimiento afecta el resultado mensual.'),
        ),
    ]
